/* Removes everything this project created. Irreversible after Time Travel expires. */
USE ROLE ACCOUNTADMIN;

ALTER TASK IF EXISTS WM_MICRO.UTIL.TSK_EOD_ROOT SUSPEND;
ALTER TASK IF EXISTS WM_MICRO.RT.TSK_MERGE_INTRADAY_TRADE SUSPEND;

DROP SHARE IF EXISTS WM_CLIENT_AUM_SHARE;
DROP DATABASE IF EXISTS WM_MICRO_QA;
DROP DATABASE IF EXISTS WM_MICRO;            -- UNDROP DATABASE WM_MICRO; works within retention
DROP WAREHOUSE IF EXISTS WM_LOAD_WH;
DROP WAREHOUSE IF EXISTS WM_TRANSFORM_WH;
DROP WAREHOUSE IF EXISTS WM_BI_WH;
DROP RESOURCE MONITOR IF EXISTS WM_RM;
DROP INTEGRATION IF EXISTS WM_S3_INT;
DROP INTEGRATION IF EXISTS WM_EMAIL_INT;
DROP ROLE IF EXISTS WM_ADVISOR_201;
DROP ROLE IF EXISTS WM_PII_READER;
DROP ROLE IF EXISTS WM_ANALYST;
DROP ROLE IF EXISTS WM_TRANSFORMER;
DROP ROLE IF EXISTS WM_LOADER;
