-- Run once as ACCOUNTADMIN (or SECURITYADMIN + SYSADMIN) in a Snowsight worksheet.
-- Creates an isolated warehouse / database / role for this micro project.

USE ROLE SYSADMIN;

CREATE WAREHOUSE IF NOT EXISTS WM_WH
  WAREHOUSE_SIZE = 'XSMALL'
  AUTO_SUSPEND = 60          -- seconds; keeps credit burn tiny
  AUTO_RESUME = TRUE
  INITIALLY_SUSPENDED = TRUE;

CREATE DATABASE IF NOT EXISTS WM_MICRO
  DATA_RETENTION_TIME_IN_DAYS = 1;

USE ROLE SECURITYADMIN;

CREATE ROLE IF NOT EXISTS WM_TRANSFORMER;
GRANT ROLE WM_TRANSFORMER TO ROLE SYSADMIN;   -- keep role hierarchy intact

GRANT USAGE, OPERATE ON WAREHOUSE WM_WH TO ROLE WM_TRANSFORMER;
GRANT USAGE, CREATE SCHEMA ON DATABASE WM_MICRO TO ROLE WM_TRANSFORMER;

-- Give the role to yourself (replace with your user name)
GRANT ROLE WM_TRANSFORMER TO USER IDENTIFIER($MY_USER);
-- e.g.  SET MY_USER = 'KUMARA';  before running the line above

-- Optional: a resource monitor so a runaway query can't burn credits
USE ROLE ACCOUNTADMIN;
CREATE RESOURCE MONITOR IF NOT EXISTS WM_RM
  WITH CREDIT_QUOTA = 5 FREQUENCY = MONTHLY START_TIMESTAMP = IMMEDIATELY
  TRIGGERS ON 80 PERCENT DO NOTIFY
           ON 100 PERCENT DO SUSPEND;
ALTER WAREHOUSE WM_WH SET RESOURCE_MONITOR = WM_RM;
